const { ROLES } = require('./constants');

const permissions = {
  branches: {
    create: [ROLES.ADMIN],
    read: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
    readOne: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
    update: [ROLES.ADMIN, ROLES.MANAGER],
    delete: [ROLES.ADMIN],
    updateStatus: [ROLES.ADMIN, ROLES.MANAGER],
  },
  vehicles: {
    create: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.CUSTOMER],
    read: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.CUSTOMER],
    update: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.CUSTOMER],
    delete: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.CUSTOMER],
  },
  packages: {
    create: [ROLES.ADMIN],
    read: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.CUSTOMER],
    readOne: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.CUSTOMER],
    update: [ROLES.ADMIN],
    delete: [ROLES.ADMIN],
  },
  bookings: {
    create: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.CUSTOMER],
    readAll: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
    readOne: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.CUSTOMER],
    update: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
    updateStatus: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
    cancel: [ROLES.ADMIN, ROLES.MANAGER, ROLES.CUSTOMER],
    delete: [ROLES.ADMIN],
    slots: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.CUSTOMER],
  },
  payments: {
    create: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.CUSTOMER],
    readAll: [ROLES.ADMIN, ROLES.MANAGER],
    readOne: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF, ROLES.CUSTOMER],
    confirm: [ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF],
    refund: [ROLES.ADMIN, ROLES.MANAGER],
  },
};

module.exports = { permissions, ROLES };
